name: Release Electron app

on:
  push:
    branches: 
      - stable

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'

      - name: Extract version info
        id: version
        run: echo ${npm pkg get version} >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: npm install
        working-directory: webapp

      - name: Build n Package
        run: npm run package
        working-directory: webapp

      - name: Publish
        run: npm run publish
        working-directory: webapp
      
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{steps.version.outputs}}',
              sha: context.sha
            })

      # - name: release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     files: |
      #       dist/*.exe
      #       dist/*.zip
      #       dist/*.dmg
      #       dist/*.AppImage
      #       dist/*.snap
      #       dist/*.deb
      #       dist/*.rpm
      #       dist/*.tar.gz
      #       dist/*.yml
      #       dist/*.blockmap
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY }}