name: Release Electron app

on:
  workflow_dispatch: 
  # pull_request:
  #   branches: 
  #     - stable

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'

      - name: Extract version info
        id: version
        run: echo ${npm pkg get version} >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: npm ci
        working-directory: webapp

      - name: Build n Package
        run: npm run package
        working-directory: webapp
    
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:

      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.DEPLOY_KEY}}

      