name: Release Electron app

on:
  workflow_dispatch: 
  # pull_request:
  #   branches: 
  #     - stable

jobs:
    
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/workflows/build.yaml

      - name: Semantic release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.DEPLOY_KEY}}

      