name: Release
on:
  workflow_dispatch: 
  # pull_request:
  #   branches: 
  #     - stable

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'

      - name: Install Dependencies
        run: npm ci
        working-directory: webapp

      - name: Build n Package
        run: npm run package
        working-directory: webapp

      - name: Stats
        run: ls -la dist
        working-directory: webapp

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}}
          path: webapp/dist
    
  release:
    needs: build
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: 'webapp/package-lock.json'

      - name: Install Dependencies
        run: npm ci
        working-directory: webapp

      - name: Download all distributions
        uses: actions/download-artifact@v4
        with:
          path: webapp/

      - name: Semantic release
        run: npx semantic-release
        working-directory: webapp
        env:
          GITHUB_TOKEN: ${{secrets.DEPLOY_KEY}}

      